spring:
  datasource:
    url: jdbc:mysql://10.211.55.3:3306/webtest
    username: webtesting
    password: webtesting
    driver-class-name: com.mysql.jdbc.Driver
  data:
    rest:
      base-path: /api
      default-page-size: 10
      max-page-size: 10
server:
  port: 8081